### ISSUE TITLE
Documentation regarding binding on translation attribute

### ISSUE THREAD

**Issue by Vlemert** [zewa666/aurelia-i18next#27]
The following snippet doesn't work, because Aurelia can't/won't bind on non-existent html attributes:
```html
<label i18n="${someVar}"></label>
```

The solution to this is to prepend the attribute with "data-"
```html
<label data-i18n="${someVar}"></label>
```

And register this attribute during setup:
```javascript
...
instance.setup({
    ...
    attributes : ['data-i18n'],
    ...
});
...
```

I think this would make a great addition to the documentation / readme.

**Comment by zewa666** [comment]
Hmmm I'm not sure why this shouldn't work. The default attributes registered are `t` and `i18n`. https://github.com/zewa666/aurelia-i18next/blob/master/src/i18n.js#L25

I've just tried one of the unit tests and it works for me, so I'm not sure whether the issue for you happens because of a different problem. Can you create a small example and uploading it to Plunkr or a Github repo depicting the problem?
