### ISSUE TITLE
Translating after condition change

### ISSUE THREAD

**Issue by Mordred** [zewa666/aurelia-i18next#32]
```html
<div class="alert alert-info" if.bind="showInfo">
  <span t="Translate">Not translated</span>
</div>
```

If the `showInfo` becomes `true`, translations are not evaluated and the `Not translated` text will be displayed.

**Comment by zewa666** [comment]
I have a fix but its not complete for release as I'm missing one part. In order to make this work we'd simply have to create an Aurelia Custom Attribute out of your used Translation-Attributes. Inside there, whenever the value changes or the thingy is initialized the first time, we can call the translation service automatically.

Now the only problem that I've left is to learn how to register an attribute with multiple names so that whatever the user provides can be used as the alias for the custom attribute.

**Comment by zewa666** [comment]
Ok so at least for your current approach with naming the attribute `t` the recent update should already solve your problem. Please report back if any other issues arise, will get the alias registration done in the meantime

**Comment by Mordred** [comment]
Nice, it's working now for `t` attribute. Thanks

**Comment by zewa666** [comment]
Great, thx for the feedback

**Comment by zewa666** [comment]
@Mordred the recent update now also introduces aliases

**Comment by Mordred** [comment]
Nice .. very good job
